name: scannet_pseudo_label
checkpoint_load: /home/jonfrey/results/cluster_results/2021-03-15T10:21:22_24h_lr_001/task0-epoch=120--step=444069.ckpt

loader:
  pin_memory: true
  batch_size: 1
  shuffle: false
  num_workers: 0

dataset: 
  name: scannet
  mode: test_strict
  output_size:
  - 640
  - 1280
  replay: True
  sub: 10
  cfg_replay:
    bins: 4
    elements: 100
    add_p: 0.5
    replay_p: 0.5
    current_bin: 0
  data_augmentation: False
  data_augmentation_for_replay: False

model:
  name: Fast-SCNN
  cfg:
    num_classes: 40
    aux: false
    extraction:
      active: false
      layer: learn_to_down