name: scannet_pseudo_label
checkpoint_load: cluster/2021-03-30T21:35:50_01/task0-epoch=25--step=002677.ckpt


dataset: 
  name: labdata
  mode: train
  output_size:
  - 640
  - 1280
  replay: True
  sub: 10
  cfg_replay:
    bins: 4
    elements: 100
    add_p: 0.5
    replay_p: 0.5
    current_bin: 0
  data_augmentation: False
  data_augmentation_for_replay: False

model:
  name: Fast-SCNN
  cfg:
    num_classes: 40
    aux: false
    extraction:
      active: false
      layer: learn_to_down

loader:
  pin_memory: true
  batch_size: 4
  shuffle: false
  num_workers: 4

task_generator:
  total_tasks: 4
  mode: scannet_continual_learning_count_adjusted
  seed: 0
  replay_adaptive_add_p: False
  scannet_strict_split: False
  scannet_small_factor: 4
  copy_to_template:
    output_size:
    - 640
    - 1280
    # scenes: # S
    # - scene0000
    cfg_replay:
      bins: 4
      elements: 100
      add_p: 0
      replay_p: 0.5
      current_bin: 0
    replay: False
    data_augmentation: False
    data_augmentation_for_replay: False
        