name: flow_labdata
checkpoint_load: /home/jonfrey/results/cluster_results/2021-03-15T10:21:22_24h_lr_001/task0-epoch=120--step=444069.ckpt

loader:
  pin_memory: true
  batch_size: 2
  shuffle: false
  num_workers: 0

dataset: 
  name: labdata
  mode: val
  output_size:
  - 640
  - 1280
  replay: True
  sub: 1
  cfg_replay:
    bins: 4
    elements: 100
    add_p: 0.5
    replay_p: 0.5
    current_bin: 0
  data_augmentation: False
  data_augmentation_for_replay: False

model:
  name: Fast-SCNN
  cfg:
    num_classes: 40
    aux: false
    extraction:
      active: false
      layer: learn_to_down

task_generator:
  total_tasks: 4
  mode: scannet_continual_learning
  seed: 0
  replay_adaptive_add_p: True
  scannet_strict_split: False
  copy_to_template:
    # scenes: # S
    # - scene0000
    cfg_replay:
      bins: 4
      elements: 500
      add_p: 0.5
      replay_p: 0.5
      current_bin: 0
    replay: True
    data_augmentation: True
    data_augmentation_for_replay: True