id: c63aecb41bfdfd6b7e1fac37c7cbe7bf
hardware_id: /versavis/imu
sensor_type: IMU
sigmas:
  gyro_noise_density: 0.005
  gyro_bias_random_walk_noise_density: 1.0e-03 # 4.0e-06
  acc_noise_density: 0.01
  acc_bias_random_walk_noise_density: 0.0002
saturation_accel_max_mps2: 150.0
saturation_gyro_max_radps: 7.5
gravity_magnitude_mps2: 9.81
