name: WhenStop/patience_5_minimal_increase
timestamp: true
weights_restore: true
checkpoint_restore: false
checkpoint_load: template/hypersim/task0-epoch=46.ckpt
tramac_restore: false
lr: 0.003

start_at_task: 1
max_tasks: 4

replay_state_sync_back:
  active: true
  get_size_from_task_generator: true

task_specific_early_stopping:
  patience: 5
  timelimit_in_min: 70
  minimal_increase: 0.02 #increase accuracy by 2 percent
  verbose: True

lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 1000
    target_lr: 1.0e-04
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
latent_replay_buffer:
  active: False
  cfg:
    elements: 100
    bins: 4
    injection_rate: 1
    mode: 'LIFO'
  extraction_level: input
  fill_sample_from_batch_ratio: 0.5
teaching:
  active: False
  soft_labels: True
  soft_labels_weight: 1
  loss_function: MSE
trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 1
  max_epochs: 1000
  gpus: -1
  accelerator: ddp
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 5
loader:
  pin_memory: true
  batch_size: 16
  shuffle: true
  num_workers: 16
visu:
  every_n_epochs: 1
  log_training_metric_every_n_epoch: 1
  train_images: 1
  val_images: 1
  test_images: 1
model:
  name: Fast-SCNN
  input_size: 384
  cfg:
    num_classes: 40
    aux: false
  freeze:
    active: false
    mask:
      - true
      - true
      - false 
      - false
task_generator:
  total_tasks: 4
  mode: mlhypersim_random4_tests
  cfg_replay:
    bins: 4
    elements: 50
    add_p: 0.5
    replay_p: 0.2
    current_bin: 0
  replay_adaptive_add_p: True
  replay: True
  data_augmentation: True
  data_augmentation_for_replay: True

cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001
cb_checkpoint:
  nameing: 1
  cfg:
    verbose: true
    monitor: val_loss/dataloader_idx_
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 1
lr_monitor:
  cfg:
    logging_interval: step

move_datasets:
  # - env_var: coco
  - env_var: mlhypersim
