name: mlhypersim_coco_4_fast/start_coco_finetune_mem
timestamp: false
weights_restore: true
checkpoint_restore: false
checkpoint_load: COCO/2021-01-15T19:32:57_pretrain_full_24_correct_IoU/epoch=104task_name=0-val_acc_epoch=0.49-val_mIoU_epoch=0.30.ckpt
tramac_restore: false
lr: 0.05
lr_scheduler:
  active: true
  cfg:
    power: 0.9
    max_epochs: 1000
    target_lr: 1.0e-05
optimizer:
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-05
trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 1
  max_epochs: 50
  gpus: -1
  accelerator: ddp
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 5
loader:
  pin_memory: true
  batch_size: 4
  batch_size_test: 4
  shuffle: true
  num_workers: 20
visu:
  every_n_epochs: 1
  log_training_metric_every_n_epoch: 5
  train_images: 1
  val_images: 1
  test_images: 1
model:
  name: Fast-SCNN
  input_size: 384
  cfg:
    num_classes: 41
    aux: false
  freeze:
    active: true
    mask:
      - true
      - true
      - false 
      - false
task_generator:
  mode: mlhypersim_random4_tests
d_val:
  name: nyuv2
  mode: val
  output_size: 384
  load_all: false
d_train:
  name: nyuv2
  mode: train
  output_size: 384
  load_all: false
d_test:
  name: nyuv2
  mode: val
  output_size: 384
  load_all: false
cb_early_stopping:
  active: false
  cfg:
    monitor: val_loss_epoch
    patience: 10000
    strict: true
    verbose: true
    mode: min
    min_delta: -0.0001
cb_checkpoint:
  nameing:
  - val_acc_epoch
  - val_mIoU_epoch
  cfg:
    verbose: true
    monitor: val_loss
    mode: min
    prefix: ''
    save_last: true
    save_top_k: 10
lr_monitor:
  cfg:
    logging_interval: step
latent_replay_buffer:
  active: True
  cfg:
    elements: 100
    bins: 4
    injection_rate: 1
    mode: 'LIFO'
move_datasets:
  # - env_var: coco
  - env_var: mlhypersim

  