name: 'task_expansion/logger'
timestamp: False
checkpoint_restore: False
checkpoint_load: path_to_ckpts
tramac_restore: False

lr: 1.0e-3
lr_scheduler: 
  active: True
  cfg:
    power: 0.9
    max_epochs: 320
    target_lr: 1.0e-6  #1.0e-6
optimizer: 
  name: ADAM
  sgd_cfg:
    momentum: 0.9
    weight_decay: 4.0e-5

trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 0.1
  limit_val_batches: 0.1
  limit_test_batches: 0.1
  progress_bar_refresh_rate: 1
  max_epochs:  2
  gpus: -1
  #accelerator: ddp
  profiler: False

loader:
  pin_memory: True
  batch_size: 16
  batch_size_test: 4
  shuffle: True
  num_workers: 8

visu:
  train_images: 3
  val_images: 3
  test_images: 3

model:
  name: Fast-SCNN
  cfg:
    num_classes: 19
    aux: false

d_val:
  name: cityscapes
  base_size: 1024
  crop_size: 768
  split: 'val'
  mode: 'val'
  overfit: -1

d_train:
  name: cityscapes
  base_size: 1024
  crop_size: 768
  split: 'train'
  mode: 'train'
  overfit: -1

d_test:
  name: cityscapes
  base_size: 1024
  crop_size: 768
  split: 'val'
  mode: 'testval'
  overfit: -1


cb_early_stopping:
  cfg:
    monitor: 'val_loss_epoch'
    patience: 100
    strict: True
    verbose: True
    mode: min
    min_delta: -0.0001

cb_checkpoint:
  nameing:
  - val_acc_epoch
  - val_mIoU_epoch
  cfg:
    verbose: true
    monitor: val_loss
    mode: 'min'
    prefix: ""
    save_last: true
    save_top_k: 10

lr_monitor:
  cfg:
    logging_interval: step