name: 'debug_experiment'
timestamp: False
checkpoint_restore: False
checkpoint_load: path_to_ckpts

lr: 0.01
lr_scheduler: 
  active: True
  cfg:
    power: 0.9
    max_epochs: 160
    target_lr: 1.0e-6
optimizer: 
  name: ADAM #SGD
  sgd_cfg:
    momentum: 0.9
    weight_decay: 0 #1.0e-4


trainer:
  precision: 16
  accumulate_grad_batches: 1
  fast_dev_run: false
  limit_train_batches: 10
  limit_val_batches: 10
  limit_test_batches: 1.0
  progress_bar_refresh_rate: 1
  max_epochs:  50
  gpus: -1
  #accelerator: ddp
  profiler: False

loader:
  pin_memory: True
  batch_size: 2
  shuffle: True
  num_workers: 16

visu:
  train_images: 1
  val_images: 1
  test_images: 1

model:
  name: Fast-SCNN
  cfg:
    num_classes: 19
    aux: false

d_val:
  name: cityscapes
  base_size: 1024
  crop_size: 768
  split: 'val'
  mode: 'val'
  overfit: -1

d_train:
  name: cityscapes
  base_size: 1024
  crop_size: 768
  split: 'train'
  mode: 'train'
  overfit: -1

cb_early_stopping:
  cfg:
    monitor: 'train_loss_epoch'
    patience: 10
    strict: True
    verbose: True
    mode: min
    min_delta: 0.001

cb_checkpoint:
  nameing:
  - val_acc_epoch
  - val_iou_epoch
  cfg:
    verbose: true
    monitor: val_loss
    mode: 'min'
    prefix: ""
    save_last: true
    save_top_k: 10

lr_monitor:
  cfg:
    logging_interval: step