# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: semantic_map.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="semantic_map.proto",
    package="kimera",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x12semantic_map.proto\x12\x06kimera"\xbd\x04\n\x10SemanticMapProto\x12\x44\n\x0fsemantic_blocks\x18\x01 \x03(\x0b\x32+.kimera.SemanticMapProto.SemanticBlockProto\x1a\xe2\x03\n\x12SemanticBlockProto\x12\x17\n\x0fvoxels_per_side\x18\x01 \x01(\x05\x12\x12\n\nvoxel_size\x18\x02 \x01(\x01\x12G\n\x06origin\x18\x03 \x01(\x0b\x32\x37.kimera.SemanticMapProto.SemanticBlockProto.OriginProto\x12W\n\x0fsemantic_voxels\x18\x04 \x03(\x0b\x32>.kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto\x1a.\n\x0bOriginProto\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\xcc\x01\n\x12SemanticVoxelProto\x12X\n\x05\x63olor\x18\x01 \x01(\x0b\x32I.kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto\x12\x17\n\x0fsemantic_labels\x18\x02 \x03(\x02\x12\x14\n\x0clinear_index\x18\x03 \x01(\x05\x1a-\n\nColorProto\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05'
    ),
)


_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_ORIGINPROTO = _descriptor.Descriptor(
    name="OriginProto",
    full_name="kimera.SemanticMapProto.SemanticBlockProto.OriginProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="x",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.OriginProto.x",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="y",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.OriginProto.y",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="z",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.OriginProto.z",
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=351,
    serialized_end=397,
)

_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO_COLORPROTO = _descriptor.Descriptor(
    name="ColorProto",
    full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="r",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto.r",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="g",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto.g",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="b",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto.b",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=559,
    serialized_end=604,
)

_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO = _descriptor.Descriptor(
    name="SemanticVoxelProto",
    full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="color",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.color",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="semantic_labels",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.semantic_labels",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="linear_index",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.linear_index",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO_COLORPROTO,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=400,
    serialized_end=604,
)

_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO = _descriptor.Descriptor(
    name="SemanticBlockProto",
    full_name="kimera.SemanticMapProto.SemanticBlockProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="voxels_per_side",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.voxels_per_side",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="voxel_size",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.voxel_size",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="origin",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.origin",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="semantic_voxels",
            full_name="kimera.SemanticMapProto.SemanticBlockProto.semantic_voxels",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_ORIGINPROTO,
        _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=122,
    serialized_end=604,
)

_SEMANTICMAPPROTO = _descriptor.Descriptor(
    name="SemanticMapProto",
    full_name="kimera.SemanticMapProto",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="semantic_blocks",
            full_name="kimera.SemanticMapProto.semantic_blocks",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[
        _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=31,
    serialized_end=604,
)

_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_ORIGINPROTO.containing_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO_COLORPROTO.containing_type = (
    _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO
)
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO.fields_by_name[
    "color"
].message_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO_COLORPROTO
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO.containing_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO.fields_by_name[
    "origin"
].message_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_ORIGINPROTO
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO.fields_by_name[
    "semantic_voxels"
].message_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO
_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO.containing_type = _SEMANTICMAPPROTO
_SEMANTICMAPPROTO.fields_by_name["semantic_blocks"].message_type = _SEMANTICMAPPROTO_SEMANTICBLOCKPROTO
DESCRIPTOR.message_types_by_name["SemanticMapProto"] = _SEMANTICMAPPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemanticMapProto = _reflection.GeneratedProtocolMessageType(
    "SemanticMapProto",
    (_message.Message,),
    dict(
        SemanticBlockProto=_reflection.GeneratedProtocolMessageType(
            "SemanticBlockProto",
            (_message.Message,),
            dict(
                OriginProto=_reflection.GeneratedProtocolMessageType(
                    "OriginProto",
                    (_message.Message,),
                    dict(
                        DESCRIPTOR=_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_ORIGINPROTO,
                        __module__="semantic_map_pb2"
                        # @@protoc_insertion_point(class_scope:kimera.SemanticMapProto.SemanticBlockProto.OriginProto)
                    ),
                ),
                SemanticVoxelProto=_reflection.GeneratedProtocolMessageType(
                    "SemanticVoxelProto",
                    (_message.Message,),
                    dict(
                        ColorProto=_reflection.GeneratedProtocolMessageType(
                            "ColorProto",
                            (_message.Message,),
                            dict(
                                DESCRIPTOR=_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO_COLORPROTO,
                                __module__="semantic_map_pb2"
                                # @@protoc_insertion_point(class_scope:kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto)
                            ),
                        ),
                        DESCRIPTOR=_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO_SEMANTICVOXELPROTO,
                        __module__="semantic_map_pb2"
                        # @@protoc_insertion_point(class_scope:kimera.SemanticMapProto.SemanticBlockProto.SemanticVoxelProto)
                    ),
                ),
                DESCRIPTOR=_SEMANTICMAPPROTO_SEMANTICBLOCKPROTO,
                __module__="semantic_map_pb2"
                # @@protoc_insertion_point(class_scope:kimera.SemanticMapProto.SemanticBlockProto)
            ),
        ),
        DESCRIPTOR=_SEMANTICMAPPROTO,
        __module__="semantic_map_pb2"
        # @@protoc_insertion_point(class_scope:kimera.SemanticMapProto)
    ),
)
_sym_db.RegisterMessage(SemanticMapProto)
_sym_db.RegisterMessage(SemanticMapProto.SemanticBlockProto)
_sym_db.RegisterMessage(SemanticMapProto.SemanticBlockProto.OriginProto)
_sym_db.RegisterMessage(SemanticMapProto.SemanticBlockProto.SemanticVoxelProto)
_sym_db.RegisterMessage(SemanticMapProto.SemanticBlockProto.SemanticVoxelProto.ColorProto)


# @@protoc_insertion_point(module_scope)
